insert into Sport (id, description) values (1, 'Polo aquático');
insert into Sport (id, description) values (2, 'Badminton');
insert into Sport (id, description) values (3, 'Baseball');
insert into Sport (id, description) values (4, 'Boxe');
insert into Sport (id, description) values (5, 'Basquete');
insert into Sport (id, description) values (6, 'Hóquei de Campo');
insert into Sport (id, description) values (7, 'Futebol');
insert into Sport (id, description) values (8, 'Handball');
insert into Sport (id, description) values (9, 'Judo');
insert into Sport (id, description) values (10, 'Karate');
insert into Sport (id, description) values (11, 'Rugby Sevens');
insert into Sport (id, description) values (12, 'Volei');
insert into Sport (id, description) values (13, 'Tennis');

insert into Site(id, description) values (1, 'Estádio Olímpico');
insert into Site(id, description) values (2, 'Ginásio Nacional de Yoyogi');
insert into Site(id, description) values (3, 'Ginásio Metropolitano de Tokyo');
insert into Site(id, description) values (4, 'Nippon Budokan');
insert into Site(id, description) values (5, 'Forum Internacional de Tokyo');
insert into Site(id, description) values (6, 'Jardim Palácio Imperial');
insert into Site(id, description) values (7, 'Arena Kokugikan');
insert into Site(id, description) values (8, 'Estádio Ajinomoto');
insert into Site(id, description) values (9, 'Yokohama');

insert into Country(id, description) values (1, 'Afeganistão');
insert into Country(id, description) values (2, 'África do Sul');
insert into Country(id, description) values (3, 'Angola');
insert into Country(id, description) values (4, 'Argentina');
insert into Country(id, description) values (5, 'Austrália');
insert into Country(id, description) values (6, 'Bahamas');
insert into Country(id, description) values (7, 'Bélgica');
insert into Country(id, description) values (8, 'Bolívia');
insert into Country(id, description) values (9, 'Brasil');
insert into Country(id, description) values (10, 'Bulgária');
insert into Country(id, description) values (11, 'Canadá');
insert into Country(id, description) values (12, 'Chile');
insert into Country(id, description) values (13, 'China');
insert into Country(id, description) values (14, 'Colômbia');
insert into Country(id, description) values (15, 'Cuba');
insert into Country(id, description) values (16, 'Equador');
insert into Country(id, description) values (17, 'Espanha');
insert into Country(id, description) values (18, 'Estados Unidos');
insert into Country(id, description) values (19, 'Finlândia');
insert into Country(id, description) values (20, 'França');
insert into Country(id, description) values (21, 'Gambia');
insert into Country(id, description) values (22, 'Grã-Bretanha');
insert into Country(id, description) values (23, 'Grécia');
insert into Country(id, description) values (24, 'Honduras');
insert into Country(id, description) values (25, 'Hungria');
insert into Country(id, description) values (26, 'Índia');
insert into Country(id, description) values (27, 'Irã');
insert into Country(id, description) values (28, 'Irlanda');
insert into Country(id, description) values (29, 'Itália');
insert into Country(id, description) values (30, 'Jamaica');
insert into Country(id, description) values (31, 'Japão');
insert into Country(id, description) values (32, 'Líbano');
insert into Country(id, description) values (33, 'Luxemburgo');
insert into Country(id, description) values (34, 'Malásia');
insert into Country(id, description) values (35, 'México');
insert into Country(id, description) values (36, 'Mônaco');
insert into Country(id, description) values (37, 'Nepal');
insert into Country(id, description) values (38, 'Nigéria');
insert into Country(id, description) values (39, 'Noruega');
insert into Country(id, description) values (40, 'Nova Zelândia');
insert into Country(id, description) values (41, 'Países Baixos');
insert into Country(id, description) values (42, 'Panamá');
insert into Country(id, description) values (43, 'Paraguai');
insert into Country(id, description) values (44, 'Romênia');
insert into Country(id, description) values (45, 'Russia');
insert into Country(id, description) values (46, 'Samoa');
insert into Country(id, description) values (47, 'San Marino');
insert into Country(id, description) values (48, 'Senegal');
insert into Country(id, description) values (49, 'Singapura');
insert into Country(id, description) values (50, 'Suécia');
insert into Country(id, description) values (51, 'Suíça');
insert into Country(id, description) values (52, 'Tailândia');
insert into Country(id, description) values (53, 'Turquia');
insert into Country(id, description) values (54, 'Ucrânia');
insert into Country(id, description) values (55, 'Uruguai');
insert into Country(id, description) values (56, 'Venezuela');
insert into Country(id, description) values (57, 'Zâmbia');
insert into Country(id, description) values (58, 'Alemanha');

insert into Stage(id, description) values (1, 'Eliminatórias');
insert into Stage(id, description) values (2, 'Oitavas de Final');
insert into Stage(id, description) values (3, 'Quartas de Final');
insert into Stage(id, description) values (4, 'Semifinal');
insert into Stage(id, description) values (5, 'Final');

insert into Competition (id, id_sport, id_site, id_country1, id_country2, id_stage) values (1, 7, 9, 9, 58, 1);